version: '3'
services:
  java-srv:
    build: java-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"
    command: sh -c "/wait && mvn clean spring-boot:run"
    environment:
      - WAIT_HOSTS=db:1521
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=90
      - WAIT_HOST_CONNECT_TIMEOUT=30
  
  db:
    image: gvenzl/oracle-free:latest
    environment:
      - ORACLE_PASSWORD=pass
      - APP_USER=maria
      - APP_USER_PASSWORD=pass
    ports:
      - 1521
